server:
  port: 8762

spring:
  rabbitmq:
    host: 192.168.1.99
    port: 5672
    username: root
    password: 123456

  application:
    name: service-hi

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
